service: recognition-images-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action: [
            'dynamodb:*',
            'rekognition:*',
            's3:*'
          ]
          Resource: '*'

  environment:
    TABLE_NAME: ${self:service}-blobs
    BUCKET_NAME: ${self:service}-blobs-bucket
    PROJECT_NAME: ${self:service}-blobs-project

functions:
  create_blob:
    handler: create_blob.create_blob
    events:
      - http:
          path: blobs
          method: post

  get_blobs:
    handler: get_blobs.get_blobs
    events:
      - http:
          path: blobs/{blob_id}
          method: get


  process_blob:
    handler: process_blob.process_blob
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          existing: true

  make_callback:
    handler: make_callback.make_callback
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ blobs, StreamArn ]
          filterPatterns:
            - eventName: [ MODIFY ]


resources:
  Resources:

    blobs:
      Type: AWS::DynamoDB::Table
      Properties:
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: blob_id
            AttributeType: S
        KeySchema:
          - AttributeName: blob_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    blobsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        VersioningConfiguration:
          Status: Enabled
